# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "23:47"
      timezone: "Asia/Novosibirsk"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "Update: "
    ignore:
      - dependency-name: "org.slf4j:slf4j-api"
